In [ ]:
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import numpy as np
get_ipython().run_line_magic('matplotlib','inline')

In [ ]:
pwd

'/content'

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Go to this URL in a browser: https://accounts.google.com/o/oauth2/auth?client_id=947318989803-6bn6qk8qdgf4n4g3pfee6491hc0brc4i.apps.googleusercontent.com&redirect_uri=urn%3aietf%3awg%3aoauth%3a2.0%3aoob&scope=email%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdocs.test%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdrive%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdrive.photos.readonly%20https%3a%2f%2fwww.googleapis.com%2fauth%2fpeopleapi.readonly%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdrive.activity.readonly%20https%3a%2f%2fwww.googleapis.com%2fauth%2fexperimentsandconfigs%20https%3a%2f%2fwww.googleapis.com%2fauth%2fphotos.native&response_type=code

Enter your authorization code:
4/1AX4XfWgQMtLiEdEfxBBJ_pu9U89D8_gBxp06IHR9nVLH3GeRDurzcWaknJs
Mounted at /content/drive

In [ ]:
rice_df=pd.read_csv("/content/drive/MyDrive/Thesis/Updates/Dataset/Copy of Year_wise.csv")
rice_df.head()

   Element  Aman_Rice  AUS_Rice  ...  Temperature  Rainfall  Target
0     1961      48.34     28.80  ...        25.18    211.68        0
1     1962      49.53     29.50  ...        25.16    179.08        0
2     1963      51.36     30.60  ...        25.28    189.57        0
3     1964      52.60     31.38  ...        25.44    209.28        0
4     1965      53.35     31.82  ...        25.16    198.27        0

[5 rows x 13 columns]

In [ ]:
rice_df.keys()

Index(['Element', 'Aman_Rice', 'AUS_Rice', 'Boro_Rice', 'Gross_Area',
       'Aman_Production', 'AUS_Production', 'Boro_Production',
       'Total_Production', 'Average_Yeild_Rate', 'Temperature', 'Rainfall',
       'Target '],
      dtype='object')

In [ ]:
rice_df['Element'] = pd.to_numeric(rice_df['Element'],errors = 'coerce')
rice_df['Aman_Rice'] = pd.to_numeric(rice_df['Aman_Rice'],errors = 'coerce')
rice_df['AUS_Rice'] = pd.to_numeric(rice_df['AUS_Rice'],errors = 'coerce')
rice_df['Boro_Rice'] = pd.to_numeric(rice_df['Boro_Rice'],errors = 'coerce')
rice_df['Gross_Area'] = pd.to_numeric(rice_df['Gross_Area'],errors = 'coerce')
rice_df['Aman_Production'] = pd.to_numeric(rice_df['Aman_Production'],errors = 'coerce')
rice_df['AUS_Production'] = pd.to_numeric(rice_df['AUS_Production'],errors = 'coerce')
rice_df['Boro_Production'] = pd.to_numeric(rice_df['Boro_Production'],errors = 'coerce')
rice_df['Total_Production'] = pd.to_numeric(rice_df['Total_Production'],errors = 'coerce')
rice_df['Average_Yeild_Rate'] = pd.to_numeric(rice_df['Average_Yeild_Rate'],errors = 'coerce')
rice_df['Temperature'] = pd.to_numeric(rice_df['Temperature'],errors = 'coerce')
rice_df['Rainfall'] = pd.to_numeric(rice_df['Rainfall'],errors = 'coerce')

In [ ]:
rice_df.dtypes

Element                 int64
Aman_Rice             float64
AUS_Rice              float64
Boro_Rice             float64
Gross_Area            float64
Aman_Production       float64
AUS_Production        float64
Boro_Production       float64
Total_Production      float64
Average_Yeild_Rate    float64
Temperature           float64
Rainfall              float64
Target                  int64
dtype: object

In [ ]:
rice_df.head()

   Element  Aman_Rice  AUS_Rice  ...  Temperature  Rainfall  Target
0     1961      48.34     28.80  ...        25.18    211.68        0
1     1962      49.53     29.50  ...        25.16    179.08        0
2     1963      51.36     30.60  ...        25.28    189.57        0
3     1964      52.60     31.38  ...        25.44    209.28        0
4     1965      53.35     31.82  ...        25.16    198.27        0

[5 rows x 13 columns]

In [ ]:
rice_df.tail()

    Element  Aman_Rice  AUS_Rice  ...  Temperature  Rainfall  Target
54     2015        0.0       0.0  ...        25.26    211.87        1
55     2016        0.0       0.0  ...        25.73    176.64        1
56     2017        0.0       0.0  ...        25.50    228.56        1
57     2018        0.0       0.0  ...        25.11    151.89        1
58     2019        0.0       0.0  ...        25.44    169.11        1

[5 rows x 13 columns]

In [ ]:
rice_df.shape

(59, 13)

In [ ]:
X = rice_df.iloc[:, 0:-1].values
y = rice_df.iloc[:, -1].values

In [ ]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X,y, test_size=0.2, random_state=1)

print('Shape of X train = ', X_train.shape)
print('Shape of y train = ', y_train.shape)
print('Shape of X test = ', X_test.shape)
print('Shape of y test = ', y_test.shape)

Shape of X train =  (47, 12)
Shape of y train =  (47,)
Shape of X test =  (12, 12)
Shape of y test =  (12,)

In [ ]:
from sklearn import svm
classifier = svm.SVC(kernel='linear',gamma='auto',C=2)
classifier.fit(X_train,y_train)

y_predict = classifier.predict(X_test)

In [ ]:
from sklearn.metrics import classification_report
print(classification_report(y_test,y_predict))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00         6
           1       1.00      1.00      1.00         6

    accuracy                           1.00        12
   macro avg       1.00      1.00      1.00        12
weighted avg       1.00      1.00      1.00        12